/**
 * # Exercise 3 #

 * Task: What happens when you run the following program? Why do we get that result?
 * 
 * {
 *   let foo = 'bar';
 * }
 * 
 * console.log(foo);
 * 
 * Solution 1:
 * The code will result in an error because the variable `foo` is declared within a block, but the log function attempts to call it outside of said block.
**/
